apiVersion: apps/v1
kind: Deployment
metadata:
  name: pet-store
  namespace: dev-sec-ops-in-a-box
  labels:
    app: pet-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pet-store
  template:
    metadata:
      labels:
        app: pet-store
    spec:
      containers:
        - name: pet-store
          image: 192.168.49.2:31269/pet-store:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          resources:
            requests:
              memory: "64Mi"
              cpu: "100m"
            limits:
              memory: "128Mi"
              cpu: "250m"
      imagePullSecrets:
        - name: regcred
