apiVersion: v1
kind: Service
metadata:
  name: pet-store
  namespace: dev-sec-ops-in-a-box
spec:
  type: NodePort
  selector:
    app: pet-store
  ports:
    - name: http
      port: 8080         # exposed port inside the cluster
      targetPort: 8080   # containerPort
      nodePort: 30080    # exposed on the node (you can pick a port between 30000–32767)
      protocol: TCP