apiVersion: apps/v1
kind: Deployment
metadata:
  name: registry
  namespace: registry
spec:
  replicas: 1
  selector:
    matchLabels:
      app: registry
  template:
    metadata:
      labels:
        app: registry
    spec:
      containers:
      - name: registry
        image: registry:2
        ports:
        - containerPort: 5000
        env:
        - name: REGISTRY_HTTP_TLS_CERTIFICATE
          value: /certs/tls.crt
        - name: REGISTRY_HTTP_TLS_KEY
          value: /certs/tls.key
        - name: REGISTRY_AUTH
          value: "htpasswd"
        - name: REGISTRY_AUTH_HTPASSWD_REALM
          value: "Registry Realm"
        - name: REGISTRY_AUTH_HTPASSWD_PATH
          value: "/auth/htpasswd"
        volumeMounts:
        - name: registry-storage
          mountPath: /var/lib/registry
        - name: registry-tls
          mountPath: /certs
          readOnly: true
        - name: registry-auth
          mountPath: /auth
          readOnly: true
      volumes:
      - name: registry-storage
        emptyDir: {}
      - name: registry-tls
        secret:
          secretName: registry-tls
      - name: registry-auth
        secret:
          secretName: registry-auth
---
apiVersion: v1
kind: Service
metadata:
  name: registry
  namespace: registry
spec:
  type: NodePort
  selector:
    app: registry
  ports:
    - port: 5000         # Port exposed inside the cluster
      targetPort: 5000   # Port the container listens on
      nodePort: 31269    # Port exposed outside the cluster (customizable)
      protocol: TCP
